export const etapas = [
  { id: 1, label: "Preanálisis" },
  { id: 2, label: "Visita" },
  { id: 3, label: "Confección Expediente" },
  { id: 4, label: "Enviado al Centro de Negocios (Avalúo: Condicionado)" },
  { id: 5, label: "Enviado al Centro de Negocios (Avalúo: Aprobado)" },
  { id: 6, label: "Ingreso al BANHVI (Registrado por Entidad)" },
  { id: 7, label: "Ingreso al BANHVI (Anomalías)" },
  { id: 8, label: "Ingreso al BANHVI (Emitido)" },
  { id: 9, label: "Ingreso al BANHVI (Aprobado)" },
  { id: 10, label: "Permisos de Construcción" },
  { id: 11, label: "Proceso de Formalización" },
  { id: 12, label: "Solicitud de Servicio Público" },
  { id: 13, label: "En Construcción" },
  { id: 14, label: "Entregado" },
  { id: 15, label: "Facturado" },
];
